---
fixtures:
  symlinks:
    puppet: "#{source_dir}"
  forge_modules:
    apache:
      repo: puppetlabs-apache
      ref: 1.11.1
    concat:
      repo: puppetlabs-concat
      ref: 2.2.1
    extlib:
      repo: puppet-extlib
      ref: 1.1.0
    foreman:
      repo: theforeman-foreman
      ref: 7.2.0
    git:
      repo: theforeman-git
      ref: 2.0.0
    inifile:
      repo: puppetlabs-inifile
      ref: 1.6.0
    puppetdb:
      repo: puppetlabs-puppetdb
      ref: 6.0.0
    stdlib:
      repo: puppetlabs-stdlib
      ref: 4.20.0
